Repository nossas/nossas-org, pull requests merged in 2021-06, with the labels that each got.

#15 Hotfix/details-about
  components/Employee/DrawerInfo.tsx
  components/Employee/EmployeeItem.tsx
  components/Employee/index.tsx
  components/Media/Media.tsx
  components/Timeline/index.tsx
  content/Media.tsx
  pages/about/_team.tsx
  pages/about/_timeline.tsx
  pages/about/index.tsx
  public/static/media/s3/obama-foundation.png
  public/static/media/s3/stanford.png
  public/static/media/timeline/periferia-que-faz.png
Labels: size/L

#19 Add licenciamento-ambiental-fica campaign to home/mobilizations pages
  pages/index.tsx
  pages/mobilizations/index.tsx
  public/static/locales/en/sliders.json
  public/static/locales/pt-BR/sliders.json
  public/static/media/s3/licenciamento-ambiental.png
Labels: size/M

#22 fix: remove automatic redirect on timeline
  components/Timeline/index.tsx
  pages/about/_timeline.tsx
Labels: approved, size/S

#24 fix: remove audit button
  components/Page/Section.tsx
  pages/about/index.tsx
Labels: approved, size/XS

#26 Add env secret vars
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/nossas-org/values.yaml
  package.json
Labels: approved, size/M

#28 Add env secret vars
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  charts/nossas-org/templates/secret.yaml
  charts/nossas-org/values.yaml
Labels: approved, size/M

#29 fix: Add custom env vars into release build step
  .lighthouse/jenkins-x/release.yaml
  charts/nossas-org/values.yaml
Labels: approved, size/S

#31 FIX: Mobile bugs
  components/Accordion/index.tsx
  components/Donation/CardForm.tsx
  components/Donation/Finish.tsx
  components/Navbar/NavMobile.tsx
  components/Page/useWindowSize.ts
  components/Slider/SliderPanel.tsx
  pages/about/_team.tsx
  pages/about/_timeline.tsx
  pages/about/index.tsx
  pages/index.tsx
  pages/work-with-us/index.tsx
  public/locales/en/trainings.json
  public/locales/pt-BR/about.json
  public/locales/pt-BR/trainings.json
Labels: approved, size/L

#32 Hotfix/icons
  components/Slider/ImageTextIncubations.tsx
  content/ImageTextListBox.tsx
  pages/incubations/index.tsx
Labels: approved, size/L

#36 fix: decrease carousel height
  components/Slider/Panel.tsx
Labels: approved, size/XS

#33 Change texts
  pages/about/_timeline.tsx
  pages/work-with-us/index.tsx
  public/locales/en/about.json
  public/locales/pt-BR/about.json
  public/locales/pt-BR/common.json
Labels: approved, size/S

#34 Hotfix/Accordion
  components/Accordion/index.tsx
Labels: approved, size/XS

#35 fix: post action messages in subscribe forms
  components/NewsletterForm/index.tsx
  public/locales/en/common.json
  public/locales/en/incubations.json
  public/locales/en/materials.json
Labels: approved, size/S

#39 Revert Translate Button
  components/I18nButton.tsx
  next-i18next.config.js
Labels: approved, size/M

#42 Adiciona monitoramento a página
  lib/apm.ts
  package.json
  pages/_app.tsx
  yarn.lock
Labels: approved, size/M

#37 feat: show menu when scroll up on mobile
  components/Navbar/Elements.tsx
Labels: approved, size/M

#41 Autofire i18n
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  Dockerfile
  charts/nossas-org/templates/secret.yaml
  components/Donation/index.tsx
  components/NewsletterForm/index.tsx
  content/SubscribeForm/index.tsx
  content/SubscribeForm/settings.ts
  pages/incubations/index.tsx
  pages/materials/index.tsx
  pages/work-with-us/index.tsx
Labels: approved, size/M

#43 fix: update texts in english
  content/ImageTextListBox.tsx
  pages/about/_timeline.tsx
  pages/incubations/index.tsx
  pages/technologies/index.tsx
  pages/trainings/index.tsx
  public/locales/en/about.json
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/en/incubations.json
  public/locales/en/materials.json
  public/locales/en/mobilizations.json
  public/locales/en/technologies.json
  public/locales/en/trainings.json
  public/locales/pt-BR/about.json
  public/locales/pt-BR/incubations.json
  public/locales/pt-BR/trainings.json
  public/static/media/s3/depoimento.jpg
  public/static/media/s3/depoimento.png
  public/static/media/s3/depoimento2.jpg
  public/static/media/s3/depoimento2.png
  public/static/media/s3/depoimento3.jpg
  public/static/media/s3/depoimento3.png
Labels: approved, size/L

#44 Final changes - home/incubations/mobilizations/trainings pages
  pages/incubations/index.tsx
  public/locales/en/about.json
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/en/mobilizations.json
  public/locales/en/trainings.json
Labels: approved, size/M

#45 Revert revert
  components/I18nButton.tsx
  next-i18next.config.js
Labels: approved, size/M

#46 fix: use Link next to navigation pages mobile
  components/Navbar/MenuItemsMobile.tsx
Labels: approved, size/XS

#47 Ajustes nos textos em Inglês
  content/Media.tsx
  public/locales/en/incubations.json
  public/locales/en/materials.json
  public/locales/en/technologies.json
Labels: approved, size/L

#48 fix: fix incubations carousel
  pages/incubations/index.tsx
  public/locales/en/incubations.json
  public/locales/pt-BR/incubations.json
Labels: approved, size/M

#50 chore: update secrets
  charts/nossas-org/templates/secret.yaml
  charts/nossas-org/values.yaml
Labels: approved, size/M

#51 Hotfix/adjustments
  components/Navbar/Elements.tsx
  components/Slider/ImageTextIncubations.tsx
  pages/about/_team.tsx
  pages/about/_timeline.tsx
  pages/incubations/index.tsx
  public/locales/en/about.json
  public/locales/en/incubations.json
  public/locales/pt-BR/about.json
  public/locales/pt-BR/common.json
  public/static/media/timeline/EN/nfpt.png
  public/static/media/timeline/PT/4gpraestudantes.png
  public/static/media/timeline/PT/amarildosepriscilas.png
  public/static/media/timeline/PT/amazoniacontracovid.png
  public/static/media/timeline/PT/beta.png
  public/static/media/timeline/PT/bonde.png
  public/static/media/timeline/PT/canudos-sp.png
  public/static/media/timeline/PT/canudos.png
  public/static/media/timeline/PT/covidnasfavelas.png
  public/static/media/timeline/PT/defezap.png
  public/static/media/timeline/PT/instintodevida.png
  public/static/media/timeline/PT/mapadoacolhimento.png
  public/static/media/timeline/PT/maraton.png
  public/static/media/timeline/PT/meurio.png
  public/static/media/timeline/PT/minhasampa.png
  public/static/media/timeline/PT/naovaitermesada.png
  public/static/media/timeline/PT/nfpt.png
  public/static/media/timeline/PT/nossas.png
  public/static/media/timeline/PT/paulistaaberta.png
  public/static/media/timeline/PT/pec29.png
  public/static/media/timeline/PT/periferia-que-faz.png
  public/static/media/timeline/PT/periferiaquefaz.png
  public/static/media/timeline/PT/programamobilizadores.png
  public/static/media/timeline/PT/rendabasica.png
  public/static/media/timeline/PT/rnc.png
  public/static/media/timeline/PT/semaulassemenem.png
  public/static/media/timeline/PT/somoscria.png
  public/static/media/timeline/PT/violencianaotemhora.png
  public/static/media/timeline/PT/vitoria.png
Labels: approved, size/L

#53 Hotfix/adjustments
  components/Accordion/index.tsx
  components/IconsSVG/Functionalities/ComputerBlue.tsx
  components/IconsSVG/Functionalities/index.ts
  pages/work-with-us/index.tsx
  public/locales/en/about.json
  public/locales/pt-BR/about.json
Labels: approved, size/M

#54 fix: fix cover title on About page
  components/Hero/Hero.tsx
  pages/about/index.tsx
Labels: approved, size/XS

#56 Hotfix/refactor responsiveness
  components/Accordion/index.tsx
  components/Employee/index.tsx
  components/Footer/Footer.tsx
  components/Hero/Hero.tsx
  components/Navbar/Elements.tsx
  components/Page/Section.tsx
  content/ContentMedia.tsx
  content/DescriptionBox.tsx
  content/ImageTextListBox.tsx
  content/WeAreDoing.tsx
  pages/about/_impactNumber.tsx
  pages/about/index.tsx
  pages/incubations/index.tsx
  pages/index.tsx
  pages/materials/index.tsx
  pages/trainings/index.tsx
  pages/work-with-us/index.tsx
  public/locales/en/about.json
  public/locales/en/common.json
  public/locales/en/home.json
  public/locales/en/incubations.json
  public/locales/en/materials.json
  public/locales/en/technologies.json
  public/locales/en/trainings.json
  public/static/media/team/alessandra-orofino.png
  public/static/media/team/anderson-bento.png
  public/static/media/team/daniela-orofino.png
  public/static/media/team/enrica-duncan.png
  public/static/media/team/gloria-teodoro.png
  public/static/media/team/ines-laffer.png
  public/static/media/team/leticia-castro.png
  public/static/media/team/manoela-miklos.png
  public/static/media/team/talita-novacoski.png
  public/static/media/team/virginia.png
Labels: approved, size/L

#57 Hotfix/adjustments
  components/Employee/EmployeeItem.tsx
Labels: approved, size/S
